# Define target output
target: build

# Define TOP directory
export TOP_DIR = $(abspath $(PWD)/../..)

# If SYN.TOP is different from component name
export SYNTOP = processNetwork

# Use top level makefile
include $(TOP_DIR)/submodules/ruckus/system_vitis_unified_hls.mk
